### ISSUE TITLE
cff file

### ISSUE THREAD

**Issue by hvwaldow** [CaptainSifff/paper_teaching-learning-RSE#253]
+ Base desired citation on proper cff file.
+ cff file generated from contributors.yml through GitHub-Action.

**Comment by MakisH** [comment]
@hvwaldow and I met and created a first attempt to a CFF:

```
cff-version: 1.2.0
message: If you use this software, please cite it using these metadata.
# What do we put as a title for the repository itself, if this is a CFF for the repository itself?
title: Foundational Competencies and Responsibilities of a Research Software Engineer
abstract: "The term Research Software Engineer, or RSE, emerged a little over 10 years ago as a way to represent individuals working in the research community but focusing on software development. The term has been widely adopted and there are a number of high-level definitions of what an RSE is. However, the roles of RSEs vary depending on the institutional context they work in. At one end of the spectrum, RSE roles may look similar to a traditional research role. At the other extreme, they resemble that of a software engineer in industry. Most RSE roles inhabit the space between these two extremes. Therefore, providing a straightforward, comprehensive definition of what an RSE does and what experience, skills and competencies are required to become one is challenging. In this community paper we define the broad notion of what an RSE is, explore the different types of work they undertake, and define a list of foundational competencies as well as values that outline the general profile of an RSE. Further research and training can build upon this foundation of skills and focus on various aspects in greater detail. We expect that graduates and practitioners will have a larger and more diverse set of skills than outlined here. On this basis, we elaborate on the progression of these skills along different dimensions, looking at specific types of RSE roles, proposing recommendations for organisations, and giving examples of future specialisations. An appendix details how existing curricula fit into this framework."
authors:
  - family-names: Seibold
    given-names: Heidi
    orcid: "https://orcid.org/0000-0002-8960-9642"
    affiliation: "IGDORE Munich"
    country: DE
    email: heidi@seibold.co
  - ...
identifiers:
  - description: competencies_arxiv_v1
    type: url
    value: "https://github.com/CaptainSifff/paper_teaching-learning-RSE/releases/tag/competencies_arxiv_v1"
  - description: competencies_arxiv_v2
    type: url
    value: "https://github.com/CaptainSifff/paper_teaching-learning-RSE/releases/tag/competencies_arxiv_v2"
license: CC-BY-4.0
repository-code: "https://github.com/CaptainSifff/paper_teaching-learning-RSE"
```

Some links:

- [schema](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md)
- [basic example](https://github.com/citation-file-format/citation-file-format/blob/main/README.md#structure)
